sudo: required

language: go

go_import_path: github.com/bosh-prometheus/shield_exporter

services:
  - docker

env:
  matrix:
    - DOCKER_IMAGE_NAME=boshprometheus/shield-exporter
  global:
    - secure: fSNr/KaGUQO+lo5ywYXZHgjXTzDoFsvxZwh088ha/S+Y0IBcUzmqydOntGSfZruU81suaG+NZ+If+DkdfWc7hGUASImu40PoZMQEN5dDrSc0mIUJzAGVn+drp99Ta10vO1kMuR3G/+YFA/q6Owt0x+KZpFjS2DkU8RQccWStk0q/KsjcOHAAydRfh/GnFBKRUHKb4yJFr3ZiMIxsZRy6WIUAY/Da3kDnnuG1ava+jNbzTlkXB3Uzqmvccl5W8OAosgapy/BpZRLof2o7Y3eU19k6hvh88wX2WTYH8QlDLImz8a+2u98cROu3KnZ6k6yZxuUokOFiNq6TIN7S3ZoMk/1m+B3ikXpUj20+ylze5pPnprxvklvmC9eCYxayq7FcpYaxIj5GGxVKASMfzDUSHgQmLoKvkJlXEuJ7ibJuIexOYav8MVxj7jMCCtT6Hgeciq51ukE0EqMDPQE8DkZCbL6R1R7LFOC1eMYCTNRPFk7C7Y7D0DdlMhuBZfMa87jPWrHKr7PWo2pVUnxmzV0edRUWeQ/Tk46ttEh/v6QO4HB+lq4kXnxyJk5lWczULaxJYclnnuNJNKVmqZlWFjynIZKVAysIFSnvhI69+FsqQgmM9RSDn5yXBd/VAAZUO4dB8U60AtqrBEiNOO+kKX6blNn7c9RutPi8rAMLfbTSq38=
    - secure: TGxvRQOlYlVqgdwqMajBhb5X9BVVN81Bx/id3DXTr4FhoCPGtpEI583pSgC4hzLzOJQ8pSIPMC/FImsP406vtBc2/t7+TX0OkDoe1l84fW+a7Yh+8faOb5cgbqFehKAFpBD7foSBMkx3u9oeNBEzdG4UOj9H7wG0j4SmhtYhTyYO1/0NucG8RA7WjbtEQ5DHiwmsXl/++9eQDk1ASXI8I3vLT3b3LRv5NgP1qSSW6z3D80TA2e3caWFEzc2JUtXvDLgqNc1/x0DuQ3Xu8CPfRfulY23LeWMZ8bRDrd2m9MQtLoH0A15FWDFSN9D0jhesTlasH69/vNVqU+YSO3XgbzUBthEdHAr37184LRZ9+4Rl2JrV9kbxisdn8cKjO8QgUpZ7nRPfwW5Voew5Zq+HroeV9BDQx24B1lHOmZfXEd+XNJUhnX0QLnCUaF5fksR6D7P5ezMHjvmw3rCOWReKGQ5gBZaMWecHekHH1Q7vUU9Lh+q/y2dW42GgDwDVQo8m+HZKJgUg+UU2VCjGg0f1WLRl5d+FfuyVEWNhG4WE6wnwO9024ms0mzgq7S1sBDHCOFfxKeas+dAvniKqUBCJGE1cOFA6fQy2wj8QDINlfi3i9cSWcNitIoUs+dB6lNz9oypna+RB57/CVYPygwcTETy0qcL8Tm05/yskC7Za/bM=

jobs:
  include:
    - stage: tests
      script: make test
    - stage: docker image
      script:
        - make crossbuild
        - ln -s .build/linux-amd64/shield_exporter shield_exporter
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          fi
        - |
          if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
          fi
        - docker images
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE_NAME
          fi
